### ISSUE TITLE
Is there any .ipynb for HW01?

### ISSUE THREAD

**Issue by zita-ch** [elliottash/robot_judge_2022#1]
Sorry but I could not remember whether it was mentioned in class. 
I don't see HW01.ipynb here, but there is something to be submitted on Eduflow.
Could there be any explanations?

Thanks in advance!

**Comment by Eugleo** [comment]
The first assignment is to write a short fake news article. As per slide 38:

> Write a short fake news article (~300 words) about a fake AI technology supporting/replacing expert decisions, such as by doctors or judges. This is a completion grade – have fun with it! See EduFlow page for submission instructions.

_Disclaimer:_ I'm just another student, not a TA or anything

**Comment by zita-ch** [comment]
> 
Thanks a lot!
